version: '3.8'

services:
  web:
    build: .
    container_name: bana1bilet
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - ./database:/var/www/html/database
    restart: unless-stopped

volumes:
  vendor:
